{
  "default_stages": [
    "pre-commit"
  ],
  "repos": [
    {
      "hooks": [
        {
          "always_run": false,
          "args": ["fmt"],
          "entry": "nix",
          "exclude": "^$",
          "exclude_types": [],
          "fail_fast": false,
          "files": "\\.nix$",
          "id": "nixfmt",
          "language": "unsupported",
          "name": "nixfmt",
          "pass_filenames": true,
          "require_serial": false,
          "stages": [
            "pre-commit"
          ],
          "types": [
            "file"
          ],
          "types_or": [],
          "verbose": false
        }
      ],
      "repo": "local"
    }
  ]
}
